### ISSUE TITLE
please make app.json & easy to deploy button with buildpack requirement for heroku 

### ISSUE THREAD

**Issue by todokku** [benbusby/shoogle#1] opened 2020-04-24 13:26 UTC
Hi Ben ,
1 - please make app.json & easy to deploy button on your repo with buildpack requirement for heroku 
2 - on another cloud container , must be set chmod on run & dockerfile file's to can exutable , but my os is win , please chmod & run 2 file & re-push on your repository : 
3 - port 500 is point to 80 for run ?
log of my failed deploy : 
[Imgur](https://i.imgur.com/xVzDDhh.png)
crash problem : 
A - Previous status: ContainerCannotRun
B - OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./run\": permission denied": unknown
WAITING FOR YOUR RESPONSE
fine regards
goodbye

**Comment by benbusby** [comment] 2020-04-24 15:49
Hi todokku,

I appreciate the suggestions. I'll work on addressing these in the next couple of days, and will reach back out if I need any further clarification. 

Thanks!

**Comment by benbusby** [comment] 2020-04-25 00:24
Hi @todokku,

I just pushed a few updates addressing the changes you requested.

1. There's now [a quick deploy button in the readme](https://github.com/benbusby/shoogle#a-using-heroku-free) for deploying to heroku
2. The Dockerfile is updated to ensure the run script is executable before running the script itself, although I haven't come across this error before and haven't been able to reproduce it on any windows/mac/linux yet.
3. The port of the app uses whatever the environment variable $PORT is set to, or 5000 if it isn't set. This allows for things like deploying to Heroku where they set their own $PORT value, so that the port number doesn't have to be hardcoded within the `run` script itself. You can, however, manually update the `run` script to use whichever port you want. 

Let me know if you have any other issues with getting the app working for you.

**Comment by benbusby** [comment] 2020-04-26 16:39
Closing this issue now, since it seems to be addressed!

**Closed by benbusby** 2020-04-26 16:39 UTC
